/*
 * Cisco Intersight
 *
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2022-02-14T08:05:27Z.
 *
 * API version: 0.0.1-38392
 * Contact: intersight@cisco.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"reflect"
	"strings"
)

// TestcryptTokenApi Mo to test encryption token APIs.
type TestcryptTokenApi struct {
	MoBaseMo
	// The fully-qualified name of the instantiated, concrete type. This property is used as a discriminator to identify the type of the payload when marshaling and unmarshaling data.
	ClassId string `json:"ClassId"`
	// The fully-qualified name of the instantiated, concrete type. The value should be the same as the 'ClassId' property.
	ObjectType string `json:"ObjectType"`
	// The session identifier to be used to create/read/update or delete Encryption token. This could be a user's (web) session id or api key id, etc.
	SessionId            *string                 `json:"SessionId,omitempty"`
	Account              *IamAccountRelationship `json:"Account,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TestcryptTokenApi TestcryptTokenApi

// NewTestcryptTokenApi instantiates a new TestcryptTokenApi object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTestcryptTokenApi(classId string, objectType string) *TestcryptTokenApi {
	this := TestcryptTokenApi{}
	this.ClassId = classId
	this.ObjectType = objectType
	return &this
}

// NewTestcryptTokenApiWithDefaults instantiates a new TestcryptTokenApi object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTestcryptTokenApiWithDefaults() *TestcryptTokenApi {
	this := TestcryptTokenApi{}
	var classId string = "testcrypt.TokenApi"
	this.ClassId = classId
	var objectType string = "testcrypt.TokenApi"
	this.ObjectType = objectType
	return &this
}

// GetClassId returns the ClassId field value
func (o *TestcryptTokenApi) GetClassId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClassId
}

// GetClassIdOk returns a tuple with the ClassId field value
// and a boolean to check if the value has been set.
func (o *TestcryptTokenApi) GetClassIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassId, true
}

// SetClassId sets field value
func (o *TestcryptTokenApi) SetClassId(v string) {
	o.ClassId = v
}

// GetObjectType returns the ObjectType field value
func (o *TestcryptTokenApi) GetObjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *TestcryptTokenApi) GetObjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *TestcryptTokenApi) SetObjectType(v string) {
	o.ObjectType = v
}

// GetSessionId returns the SessionId field value if set, zero value otherwise.
func (o *TestcryptTokenApi) GetSessionId() string {
	if o == nil || o.SessionId == nil {
		var ret string
		return ret
	}
	return *o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestcryptTokenApi) GetSessionIdOk() (*string, bool) {
	if o == nil || o.SessionId == nil {
		return nil, false
	}
	return o.SessionId, true
}

// HasSessionId returns a boolean if a field has been set.
func (o *TestcryptTokenApi) HasSessionId() bool {
	if o != nil && o.SessionId != nil {
		return true
	}

	return false
}

// SetSessionId gets a reference to the given string and assigns it to the SessionId field.
func (o *TestcryptTokenApi) SetSessionId(v string) {
	o.SessionId = &v
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *TestcryptTokenApi) GetAccount() IamAccountRelationship {
	if o == nil || o.Account == nil {
		var ret IamAccountRelationship
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestcryptTokenApi) GetAccountOk() (*IamAccountRelationship, bool) {
	if o == nil || o.Account == nil {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *TestcryptTokenApi) HasAccount() bool {
	if o != nil && o.Account != nil {
		return true
	}

	return false
}

// SetAccount gets a reference to the given IamAccountRelationship and assigns it to the Account field.
func (o *TestcryptTokenApi) SetAccount(v IamAccountRelationship) {
	o.Account = &v
}

func (o TestcryptTokenApi) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedMoBaseMo, errMoBaseMo := json.Marshal(o.MoBaseMo)
	if errMoBaseMo != nil {
		return []byte{}, errMoBaseMo
	}
	errMoBaseMo = json.Unmarshal([]byte(serializedMoBaseMo), &toSerialize)
	if errMoBaseMo != nil {
		return []byte{}, errMoBaseMo
	}
	if true {
		toSerialize["ClassId"] = o.ClassId
	}
	if true {
		toSerialize["ObjectType"] = o.ObjectType
	}
	if o.SessionId != nil {
		toSerialize["SessionId"] = o.SessionId
	}
	if o.Account != nil {
		toSerialize["Account"] = o.Account
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *TestcryptTokenApi) UnmarshalJSON(bytes []byte) (err error) {
	type TestcryptTokenApiWithoutEmbeddedStruct struct {
		// The fully-qualified name of the instantiated, concrete type. This property is used as a discriminator to identify the type of the payload when marshaling and unmarshaling data.
		ClassId string `json:"ClassId"`
		// The fully-qualified name of the instantiated, concrete type. The value should be the same as the 'ClassId' property.
		ObjectType string `json:"ObjectType"`
		// The session identifier to be used to create/read/update or delete Encryption token. This could be a user's (web) session id or api key id, etc.
		SessionId *string                 `json:"SessionId,omitempty"`
		Account   *IamAccountRelationship `json:"Account,omitempty"`
	}

	varTestcryptTokenApiWithoutEmbeddedStruct := TestcryptTokenApiWithoutEmbeddedStruct{}

	err = json.Unmarshal(bytes, &varTestcryptTokenApiWithoutEmbeddedStruct)
	if err == nil {
		varTestcryptTokenApi := _TestcryptTokenApi{}
		varTestcryptTokenApi.ClassId = varTestcryptTokenApiWithoutEmbeddedStruct.ClassId
		varTestcryptTokenApi.ObjectType = varTestcryptTokenApiWithoutEmbeddedStruct.ObjectType
		varTestcryptTokenApi.SessionId = varTestcryptTokenApiWithoutEmbeddedStruct.SessionId
		varTestcryptTokenApi.Account = varTestcryptTokenApiWithoutEmbeddedStruct.Account
		*o = TestcryptTokenApi(varTestcryptTokenApi)
	} else {
		return err
	}

	varTestcryptTokenApi := _TestcryptTokenApi{}

	err = json.Unmarshal(bytes, &varTestcryptTokenApi)
	if err == nil {
		o.MoBaseMo = varTestcryptTokenApi.MoBaseMo
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "ClassId")
		delete(additionalProperties, "ObjectType")
		delete(additionalProperties, "SessionId")
		delete(additionalProperties, "Account")

		// remove fields from embedded structs
		reflectMoBaseMo := reflect.ValueOf(o.MoBaseMo)
		for i := 0; i < reflectMoBaseMo.Type().NumField(); i++ {
			t := reflectMoBaseMo.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTestcryptTokenApi struct {
	value *TestcryptTokenApi
	isSet bool
}

func (v NullableTestcryptTokenApi) Get() *TestcryptTokenApi {
	return v.value
}

func (v *NullableTestcryptTokenApi) Set(val *TestcryptTokenApi) {
	v.value = val
	v.isSet = true
}

func (v NullableTestcryptTokenApi) IsSet() bool {
	return v.isSet
}

func (v *NullableTestcryptTokenApi) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTestcryptTokenApi(val *TestcryptTokenApi) *NullableTestcryptTokenApi {
	return &NullableTestcryptTokenApi{value: val, isSet: true}
}

func (v NullableTestcryptTokenApi) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTestcryptTokenApi) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
