/*
 * Cisco Intersight
 *
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2021-12-24T09:42:08Z.
 *
 * API version: 0.0.1-37430
 * Contact: intersight@cisco.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"reflect"
	"strings"
)

// TaskWorkflowAction Start a test workflow using this object.
type TaskWorkflowAction struct {
	MoBaseMo
	// The fully-qualified name of the instantiated, concrete type. This property is used as a discriminator to identify the type of the payload when marshaling and unmarshaling data.
	ClassId string `json:"ClassId"`
	// The fully-qualified name of the instantiated, concrete type. The value should be the same as the 'ClassId' property.
	ObjectType string `json:"ObjectType"`
	// Action for test workflow. * `start` - Start action for the workflow. * `stop` - Stop action for the workflow.
	Action *string `json:"Action,omitempty"`
	// Json formatted string input parameters to workflow.
	InputParams *string `json:"InputParams,omitempty"`
	// When true, this workflow type will be triggered as a dynamic workflow, if not it will be treated as a static workflow.
	IsDynamic *bool `json:"IsDynamic,omitempty"`
	// When true, the workflow will wait for previous one to complete before starting a new one.
	WaitOnDuplicate *bool `json:"WaitOnDuplicate,omitempty"`
	// Json formatted string that has the contents of the workflow context used when starting a workflow.
	WorkflowContext      *string                      `json:"WorkflowContext,omitempty"`
	WorkflowFile         NullableTaskFileDownloadInfo `json:"WorkflowFile,omitempty"`
	Account              *IamAccountRelationship      `json:"Account,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TaskWorkflowAction TaskWorkflowAction

// NewTaskWorkflowAction instantiates a new TaskWorkflowAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskWorkflowAction(classId string, objectType string) *TaskWorkflowAction {
	this := TaskWorkflowAction{}
	this.ClassId = classId
	this.ObjectType = objectType
	var action string = "start"
	this.Action = &action
	return &this
}

// NewTaskWorkflowActionWithDefaults instantiates a new TaskWorkflowAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskWorkflowActionWithDefaults() *TaskWorkflowAction {
	this := TaskWorkflowAction{}
	var classId string = "task.WorkflowAction"
	this.ClassId = classId
	var objectType string = "task.WorkflowAction"
	this.ObjectType = objectType
	var action string = "start"
	this.Action = &action
	return &this
}

// GetClassId returns the ClassId field value
func (o *TaskWorkflowAction) GetClassId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClassId
}

// GetClassIdOk returns a tuple with the ClassId field value
// and a boolean to check if the value has been set.
func (o *TaskWorkflowAction) GetClassIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassId, true
}

// SetClassId sets field value
func (o *TaskWorkflowAction) SetClassId(v string) {
	o.ClassId = v
}

// GetObjectType returns the ObjectType field value
func (o *TaskWorkflowAction) GetObjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *TaskWorkflowAction) GetObjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *TaskWorkflowAction) SetObjectType(v string) {
	o.ObjectType = v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *TaskWorkflowAction) GetAction() string {
	if o == nil || o.Action == nil {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskWorkflowAction) GetActionOk() (*string, bool) {
	if o == nil || o.Action == nil {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *TaskWorkflowAction) HasAction() bool {
	if o != nil && o.Action != nil {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *TaskWorkflowAction) SetAction(v string) {
	o.Action = &v
}

// GetInputParams returns the InputParams field value if set, zero value otherwise.
func (o *TaskWorkflowAction) GetInputParams() string {
	if o == nil || o.InputParams == nil {
		var ret string
		return ret
	}
	return *o.InputParams
}

// GetInputParamsOk returns a tuple with the InputParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskWorkflowAction) GetInputParamsOk() (*string, bool) {
	if o == nil || o.InputParams == nil {
		return nil, false
	}
	return o.InputParams, true
}

// HasInputParams returns a boolean if a field has been set.
func (o *TaskWorkflowAction) HasInputParams() bool {
	if o != nil && o.InputParams != nil {
		return true
	}

	return false
}

// SetInputParams gets a reference to the given string and assigns it to the InputParams field.
func (o *TaskWorkflowAction) SetInputParams(v string) {
	o.InputParams = &v
}

// GetIsDynamic returns the IsDynamic field value if set, zero value otherwise.
func (o *TaskWorkflowAction) GetIsDynamic() bool {
	if o == nil || o.IsDynamic == nil {
		var ret bool
		return ret
	}
	return *o.IsDynamic
}

// GetIsDynamicOk returns a tuple with the IsDynamic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskWorkflowAction) GetIsDynamicOk() (*bool, bool) {
	if o == nil || o.IsDynamic == nil {
		return nil, false
	}
	return o.IsDynamic, true
}

// HasIsDynamic returns a boolean if a field has been set.
func (o *TaskWorkflowAction) HasIsDynamic() bool {
	if o != nil && o.IsDynamic != nil {
		return true
	}

	return false
}

// SetIsDynamic gets a reference to the given bool and assigns it to the IsDynamic field.
func (o *TaskWorkflowAction) SetIsDynamic(v bool) {
	o.IsDynamic = &v
}

// GetWaitOnDuplicate returns the WaitOnDuplicate field value if set, zero value otherwise.
func (o *TaskWorkflowAction) GetWaitOnDuplicate() bool {
	if o == nil || o.WaitOnDuplicate == nil {
		var ret bool
		return ret
	}
	return *o.WaitOnDuplicate
}

// GetWaitOnDuplicateOk returns a tuple with the WaitOnDuplicate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskWorkflowAction) GetWaitOnDuplicateOk() (*bool, bool) {
	if o == nil || o.WaitOnDuplicate == nil {
		return nil, false
	}
	return o.WaitOnDuplicate, true
}

// HasWaitOnDuplicate returns a boolean if a field has been set.
func (o *TaskWorkflowAction) HasWaitOnDuplicate() bool {
	if o != nil && o.WaitOnDuplicate != nil {
		return true
	}

	return false
}

// SetWaitOnDuplicate gets a reference to the given bool and assigns it to the WaitOnDuplicate field.
func (o *TaskWorkflowAction) SetWaitOnDuplicate(v bool) {
	o.WaitOnDuplicate = &v
}

// GetWorkflowContext returns the WorkflowContext field value if set, zero value otherwise.
func (o *TaskWorkflowAction) GetWorkflowContext() string {
	if o == nil || o.WorkflowContext == nil {
		var ret string
		return ret
	}
	return *o.WorkflowContext
}

// GetWorkflowContextOk returns a tuple with the WorkflowContext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskWorkflowAction) GetWorkflowContextOk() (*string, bool) {
	if o == nil || o.WorkflowContext == nil {
		return nil, false
	}
	return o.WorkflowContext, true
}

// HasWorkflowContext returns a boolean if a field has been set.
func (o *TaskWorkflowAction) HasWorkflowContext() bool {
	if o != nil && o.WorkflowContext != nil {
		return true
	}

	return false
}

// SetWorkflowContext gets a reference to the given string and assigns it to the WorkflowContext field.
func (o *TaskWorkflowAction) SetWorkflowContext(v string) {
	o.WorkflowContext = &v
}

// GetWorkflowFile returns the WorkflowFile field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TaskWorkflowAction) GetWorkflowFile() TaskFileDownloadInfo {
	if o == nil || o.WorkflowFile.Get() == nil {
		var ret TaskFileDownloadInfo
		return ret
	}
	return *o.WorkflowFile.Get()
}

// GetWorkflowFileOk returns a tuple with the WorkflowFile field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskWorkflowAction) GetWorkflowFileOk() (*TaskFileDownloadInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.WorkflowFile.Get(), o.WorkflowFile.IsSet()
}

// HasWorkflowFile returns a boolean if a field has been set.
func (o *TaskWorkflowAction) HasWorkflowFile() bool {
	if o != nil && o.WorkflowFile.IsSet() {
		return true
	}

	return false
}

// SetWorkflowFile gets a reference to the given NullableTaskFileDownloadInfo and assigns it to the WorkflowFile field.
func (o *TaskWorkflowAction) SetWorkflowFile(v TaskFileDownloadInfo) {
	o.WorkflowFile.Set(&v)
}

// SetWorkflowFileNil sets the value for WorkflowFile to be an explicit nil
func (o *TaskWorkflowAction) SetWorkflowFileNil() {
	o.WorkflowFile.Set(nil)
}

// UnsetWorkflowFile ensures that no value is present for WorkflowFile, not even an explicit nil
func (o *TaskWorkflowAction) UnsetWorkflowFile() {
	o.WorkflowFile.Unset()
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *TaskWorkflowAction) GetAccount() IamAccountRelationship {
	if o == nil || o.Account == nil {
		var ret IamAccountRelationship
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskWorkflowAction) GetAccountOk() (*IamAccountRelationship, bool) {
	if o == nil || o.Account == nil {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *TaskWorkflowAction) HasAccount() bool {
	if o != nil && o.Account != nil {
		return true
	}

	return false
}

// SetAccount gets a reference to the given IamAccountRelationship and assigns it to the Account field.
func (o *TaskWorkflowAction) SetAccount(v IamAccountRelationship) {
	o.Account = &v
}

func (o TaskWorkflowAction) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedMoBaseMo, errMoBaseMo := json.Marshal(o.MoBaseMo)
	if errMoBaseMo != nil {
		return []byte{}, errMoBaseMo
	}
	errMoBaseMo = json.Unmarshal([]byte(serializedMoBaseMo), &toSerialize)
	if errMoBaseMo != nil {
		return []byte{}, errMoBaseMo
	}
	if true {
		toSerialize["ClassId"] = o.ClassId
	}
	if true {
		toSerialize["ObjectType"] = o.ObjectType
	}
	if o.Action != nil {
		toSerialize["Action"] = o.Action
	}
	if o.InputParams != nil {
		toSerialize["InputParams"] = o.InputParams
	}
	if o.IsDynamic != nil {
		toSerialize["IsDynamic"] = o.IsDynamic
	}
	if o.WaitOnDuplicate != nil {
		toSerialize["WaitOnDuplicate"] = o.WaitOnDuplicate
	}
	if o.WorkflowContext != nil {
		toSerialize["WorkflowContext"] = o.WorkflowContext
	}
	if o.WorkflowFile.IsSet() {
		toSerialize["WorkflowFile"] = o.WorkflowFile.Get()
	}
	if o.Account != nil {
		toSerialize["Account"] = o.Account
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *TaskWorkflowAction) UnmarshalJSON(bytes []byte) (err error) {
	type TaskWorkflowActionWithoutEmbeddedStruct struct {
		// The fully-qualified name of the instantiated, concrete type. This property is used as a discriminator to identify the type of the payload when marshaling and unmarshaling data.
		ClassId string `json:"ClassId"`
		// The fully-qualified name of the instantiated, concrete type. The value should be the same as the 'ClassId' property.
		ObjectType string `json:"ObjectType"`
		// Action for test workflow. * `start` - Start action for the workflow. * `stop` - Stop action for the workflow.
		Action *string `json:"Action,omitempty"`
		// Json formatted string input parameters to workflow.
		InputParams *string `json:"InputParams,omitempty"`
		// When true, this workflow type will be triggered as a dynamic workflow, if not it will be treated as a static workflow.
		IsDynamic *bool `json:"IsDynamic,omitempty"`
		// When true, the workflow will wait for previous one to complete before starting a new one.
		WaitOnDuplicate *bool `json:"WaitOnDuplicate,omitempty"`
		// Json formatted string that has the contents of the workflow context used when starting a workflow.
		WorkflowContext *string                      `json:"WorkflowContext,omitempty"`
		WorkflowFile    NullableTaskFileDownloadInfo `json:"WorkflowFile,omitempty"`
		Account         *IamAccountRelationship      `json:"Account,omitempty"`
	}

	varTaskWorkflowActionWithoutEmbeddedStruct := TaskWorkflowActionWithoutEmbeddedStruct{}

	err = json.Unmarshal(bytes, &varTaskWorkflowActionWithoutEmbeddedStruct)
	if err == nil {
		varTaskWorkflowAction := _TaskWorkflowAction{}
		varTaskWorkflowAction.ClassId = varTaskWorkflowActionWithoutEmbeddedStruct.ClassId
		varTaskWorkflowAction.ObjectType = varTaskWorkflowActionWithoutEmbeddedStruct.ObjectType
		varTaskWorkflowAction.Action = varTaskWorkflowActionWithoutEmbeddedStruct.Action
		varTaskWorkflowAction.InputParams = varTaskWorkflowActionWithoutEmbeddedStruct.InputParams
		varTaskWorkflowAction.IsDynamic = varTaskWorkflowActionWithoutEmbeddedStruct.IsDynamic
		varTaskWorkflowAction.WaitOnDuplicate = varTaskWorkflowActionWithoutEmbeddedStruct.WaitOnDuplicate
		varTaskWorkflowAction.WorkflowContext = varTaskWorkflowActionWithoutEmbeddedStruct.WorkflowContext
		varTaskWorkflowAction.WorkflowFile = varTaskWorkflowActionWithoutEmbeddedStruct.WorkflowFile
		varTaskWorkflowAction.Account = varTaskWorkflowActionWithoutEmbeddedStruct.Account
		*o = TaskWorkflowAction(varTaskWorkflowAction)
	} else {
		return err
	}

	varTaskWorkflowAction := _TaskWorkflowAction{}

	err = json.Unmarshal(bytes, &varTaskWorkflowAction)
	if err == nil {
		o.MoBaseMo = varTaskWorkflowAction.MoBaseMo
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "ClassId")
		delete(additionalProperties, "ObjectType")
		delete(additionalProperties, "Action")
		delete(additionalProperties, "InputParams")
		delete(additionalProperties, "IsDynamic")
		delete(additionalProperties, "WaitOnDuplicate")
		delete(additionalProperties, "WorkflowContext")
		delete(additionalProperties, "WorkflowFile")
		delete(additionalProperties, "Account")

		// remove fields from embedded structs
		reflectMoBaseMo := reflect.ValueOf(o.MoBaseMo)
		for i := 0; i < reflectMoBaseMo.Type().NumField(); i++ {
			t := reflectMoBaseMo.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTaskWorkflowAction struct {
	value *TaskWorkflowAction
	isSet bool
}

func (v NullableTaskWorkflowAction) Get() *TaskWorkflowAction {
	return v.value
}

func (v *NullableTaskWorkflowAction) Set(val *TaskWorkflowAction) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskWorkflowAction) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskWorkflowAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskWorkflowAction(val *TaskWorkflowAction) *NullableTaskWorkflowAction {
	return &NullableTaskWorkflowAction{value: val, isSet: true}
}

func (v NullableTaskWorkflowAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskWorkflowAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
