/*
 * Cisco Intersight
 *
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2021-12-27T12:26:28Z.
 *
 * API version: 0.0.1-37434
 * Contact: intersight@cisco.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
)

// TaskFileDownloadInfoAllOf Definition of the list of properties defined in 'task.FileDownloadInfo', excluding properties defined in parent classes.
type TaskFileDownloadInfoAllOf struct {
	// The fully-qualified name of the instantiated, concrete type. This property is used as a discriminator to identify the type of the payload when marshaling and unmarshaling data.
	ClassId string `json:"ClassId"`
	// The fully-qualified name of the instantiated, concrete type. The value should be the same as the 'ClassId' property.
	ObjectType string `json:"ObjectType"`
	// When the type of the download is inline, it will read the file from the contents here.
	Contents *string `json:"Contents,omitempty"`
	// The path of the download from the specified source location for type S3, then this is the object key.
	Path *string `json:"Path,omitempty"`
	// The source of the download location and if type is S3, then this is the bucket name.
	Source *string `json:"Source,omitempty"`
	// The type of download location is captured in type. * `S3` - Download workflow from S3. * `Local` - Download workflow from local path. * `Inline` - Workflow is provided inline.
	Type                 *string `json:"Type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TaskFileDownloadInfoAllOf TaskFileDownloadInfoAllOf

// NewTaskFileDownloadInfoAllOf instantiates a new TaskFileDownloadInfoAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskFileDownloadInfoAllOf(classId string, objectType string) *TaskFileDownloadInfoAllOf {
	this := TaskFileDownloadInfoAllOf{}
	this.ClassId = classId
	this.ObjectType = objectType
	var type_ string = "S3"
	this.Type = &type_
	return &this
}

// NewTaskFileDownloadInfoAllOfWithDefaults instantiates a new TaskFileDownloadInfoAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskFileDownloadInfoAllOfWithDefaults() *TaskFileDownloadInfoAllOf {
	this := TaskFileDownloadInfoAllOf{}
	var classId string = "task.FileDownloadInfo"
	this.ClassId = classId
	var objectType string = "task.FileDownloadInfo"
	this.ObjectType = objectType
	var type_ string = "S3"
	this.Type = &type_
	return &this
}

// GetClassId returns the ClassId field value
func (o *TaskFileDownloadInfoAllOf) GetClassId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClassId
}

// GetClassIdOk returns a tuple with the ClassId field value
// and a boolean to check if the value has been set.
func (o *TaskFileDownloadInfoAllOf) GetClassIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassId, true
}

// SetClassId sets field value
func (o *TaskFileDownloadInfoAllOf) SetClassId(v string) {
	o.ClassId = v
}

// GetObjectType returns the ObjectType field value
func (o *TaskFileDownloadInfoAllOf) GetObjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *TaskFileDownloadInfoAllOf) GetObjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *TaskFileDownloadInfoAllOf) SetObjectType(v string) {
	o.ObjectType = v
}

// GetContents returns the Contents field value if set, zero value otherwise.
func (o *TaskFileDownloadInfoAllOf) GetContents() string {
	if o == nil || o.Contents == nil {
		var ret string
		return ret
	}
	return *o.Contents
}

// GetContentsOk returns a tuple with the Contents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskFileDownloadInfoAllOf) GetContentsOk() (*string, bool) {
	if o == nil || o.Contents == nil {
		return nil, false
	}
	return o.Contents, true
}

// HasContents returns a boolean if a field has been set.
func (o *TaskFileDownloadInfoAllOf) HasContents() bool {
	if o != nil && o.Contents != nil {
		return true
	}

	return false
}

// SetContents gets a reference to the given string and assigns it to the Contents field.
func (o *TaskFileDownloadInfoAllOf) SetContents(v string) {
	o.Contents = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *TaskFileDownloadInfoAllOf) GetPath() string {
	if o == nil || o.Path == nil {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskFileDownloadInfoAllOf) GetPathOk() (*string, bool) {
	if o == nil || o.Path == nil {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *TaskFileDownloadInfoAllOf) HasPath() bool {
	if o != nil && o.Path != nil {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *TaskFileDownloadInfoAllOf) SetPath(v string) {
	o.Path = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *TaskFileDownloadInfoAllOf) GetSource() string {
	if o == nil || o.Source == nil {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskFileDownloadInfoAllOf) GetSourceOk() (*string, bool) {
	if o == nil || o.Source == nil {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *TaskFileDownloadInfoAllOf) HasSource() bool {
	if o != nil && o.Source != nil {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *TaskFileDownloadInfoAllOf) SetSource(v string) {
	o.Source = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TaskFileDownloadInfoAllOf) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskFileDownloadInfoAllOf) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TaskFileDownloadInfoAllOf) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TaskFileDownloadInfoAllOf) SetType(v string) {
	o.Type = &v
}

func (o TaskFileDownloadInfoAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["ClassId"] = o.ClassId
	}
	if true {
		toSerialize["ObjectType"] = o.ObjectType
	}
	if o.Contents != nil {
		toSerialize["Contents"] = o.Contents
	}
	if o.Path != nil {
		toSerialize["Path"] = o.Path
	}
	if o.Source != nil {
		toSerialize["Source"] = o.Source
	}
	if o.Type != nil {
		toSerialize["Type"] = o.Type
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *TaskFileDownloadInfoAllOf) UnmarshalJSON(bytes []byte) (err error) {
	varTaskFileDownloadInfoAllOf := _TaskFileDownloadInfoAllOf{}

	if err = json.Unmarshal(bytes, &varTaskFileDownloadInfoAllOf); err == nil {
		*o = TaskFileDownloadInfoAllOf(varTaskFileDownloadInfoAllOf)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "ClassId")
		delete(additionalProperties, "ObjectType")
		delete(additionalProperties, "Contents")
		delete(additionalProperties, "Path")
		delete(additionalProperties, "Source")
		delete(additionalProperties, "Type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTaskFileDownloadInfoAllOf struct {
	value *TaskFileDownloadInfoAllOf
	isSet bool
}

func (v NullableTaskFileDownloadInfoAllOf) Get() *TaskFileDownloadInfoAllOf {
	return v.value
}

func (v *NullableTaskFileDownloadInfoAllOf) Set(val *TaskFileDownloadInfoAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskFileDownloadInfoAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskFileDownloadInfoAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskFileDownloadInfoAllOf(val *TaskFileDownloadInfoAllOf) *NullableTaskFileDownloadInfoAllOf {
	return &NullableTaskFileDownloadInfoAllOf{value: val, isSet: true}
}

func (v NullableTaskFileDownloadInfoAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskFileDownloadInfoAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
